# Generated by Django 4.1.3 on 2022-12-07 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_id_user_user_id_user_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID_USER',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
