# Generated by Django 4.1.3 on 2022-12-07 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_user_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID_USER',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
