# Generated by Django 4.1.3 on 2023-01-08 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_userprofile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('ID_COURSE', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255)),
                ('DESCRIPTION', models.TextField()),
                ('LOGO', models.CharField(max_length=255)),
                ('PRICE', models.DecimalField(decimal_places=2, max_digits=10)),
                ('DURATION', models.PositiveIntegerField()),
                ('ID_CATEGORY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.category')),
            ],
            options={
                'db_table': 'Course',
                'managed': True,
            },
        ),
    ]
