# Generated by Django 4.1.3 on 2023-01-09 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeachingUnit',
            fields=[
                ('ID_TEACHINGUNIT', models.AutoField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=255)),
                ('DESCRIPTION', models.TextField()),
                ('ID_COURSE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.course')),
            ],
            options={
                'db_table': 'TeachingUnit',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.FileField(upload_to='user_pictures/'),
        ),
        migrations.CreateModel(
            name='TUMaterials',
            fields=[
                ('ID_MATERIAL', models.AutoField(primary_key=True, serialize=False)),
                ('MATERIAL', models.FileField(upload_to='materials/')),
                ('EXPLANATION', models.TextField()),
                ('ID_TEACHINGUNIT', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.teachingunit')),
            ],
            options={
                'db_table': 'TUMaterials',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CourseEnrolled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CourseEnrolled',
                'managed': True,
            },
        ),
    ]
