# Generated by Django 4.1.3 on 2023-01-10 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_teachingunit_alter_userprofile_picture_tumaterials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGrade',
            fields=[
                ('ID_GRADE', models.AutoField(primary_key=True, serialize=False)),
                ('RATE', models.PositiveIntegerField()),
                ('COMMENT', models.TextField()),
                ('ID_COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CourseGrade',
                'managed': True,
            },
        ),
    ]
