# Generated by Django 4.1.3 on 2023-01-10 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_userpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID_COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CourseOwner',
                'managed': True,
            },
        ),
    ]
