# Generated by Django 4.1.3 on 2023-01-10 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0024_courseowner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingunit',
            name='ID_COURSE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
    ]
