# Generated by Django 4.1.3 on 2023-01-11 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0025_alter_teachingunit_id_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachingunit',
            name='ID_COURSE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course'),
        ),
        migrations.AlterField(
            model_name='tumaterials',
            name='ID_TEACHINGUNIT',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.teachingunit'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Administrator',
                'managed': True,
            },
        ),
    ]
