# Generated by Django 4.1.3 on 2023-01-13 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_teachingunit_id_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineChat',
            fields=[
                ('ID_ONCH', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('link', models.CharField(max_length=255)),
                ('ID_COURSE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.course')),
            ],
            options={
                'db_table': 'OnlineChat',
                'managed': True,
            },
        ),
    ]
